### ISSUE TITLE
Superscript digits are not consistent

### ISSUE THREAD

**Issue by OriginCode** [imatpot/typst-ascii-ipa#1]
![圖片](https://user-images.githubusercontent.com/17294071/233736932-673dcb7d-1538-4f5f-955a-41aac9dc3c27.png)

Font: New Computer Modern.
Source: `#phnt(sil("1^2^3^4^5^6^7^8^9^0^"))`

**Comment by imatpot** [comment]
This is caused by Computer Modern not having all the necessary Unicode symbols. It supports ¹, ², and ³, but not ⁴, ⁵, ⁶, ⁷, ⁸, ⁹, and ⁰. Typst thus renders those digits using a fallback font. This is a limitation I may not be able to fix, but I'll see what I can do. A potential fix would be to somehow replace superscript characters with a corresponding [`#super()`](https://typst.app/docs/reference/text/super/) call, though I am not sure if this is possible as the [`#replace()`](https://typst.app/docs/reference/types/string/#methods--replace) method which the project currently uses only supports [`string`](https://typst.app/docs/reference/types/string/) but not [`content`](https://typst.app/docs/reference/types/content/).

**Comment by imatpot** [comment]
After some fiddling I have come to the conclusion that I will most likely not be able to fix this issue. Typst replaces characters in a `#super()` call with the corresponding Unicode character under the hood, leading to the same mismatch you described.

Take the following snippet:

```typ
#set text(font: "New Computer Modern")

¹²³⁴⁵⁶⁷⁸⁹⁰

#let nums = (1, 2, 3, 4, 5, 6, 7, 8, 9, 0)

#for n in nums { super[#n] }

#set text(size: .6em) // for easier comparison
#for n in nums { text[#n] }
```

It produces the following output:

![image](https://user-images.githubusercontent.com/39416660/234083756-5950d787-0074-4611-b189-fa5ba49f432a.png)

As you can see, neither of the two first lines correctly match the regular style of Computer Modern's numbers. The first one uses a fallback font to display unsupported characters (as they are "forcibly" Unicode symbols) whereas the second one changes the font size and baseline to imitate superscript symbols without falling back onto a different font.

The same snippet with Linux Libertine, which supports all 10 superscript digits:

![image](https://user-images.githubusercontent.com/39416660/234084251-3519e72c-a12b-48f2-8c94-90b896a72c23.png)

It's about as uniform as you'd expect, though the superscript symbols have been modelled slightly different to their normal counterparts.

While I cannot fix this issue unfortunately, I will add a disclaimer to the project about font support. Thank you very much for catching this problem!

**Comment by imatpot** [comment]
EDIT: This is no longer supported in [`2.0.0`](https://github.com/imatpot/typst-ascii-ipa/releases/tag/2.0.0) and up

~~As a workaround, I have added a `override-font` flag to the converters which forces the output to be rendered using Linux Libertine. That way you can continue using your own fonts, and use LL for IPA transcriptions.~~

```typ
#sil("1^2^3^4^5^6^7^8^9^0^", override-font: true)
```
